config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  get 'users/create'
  root to: 'sessions#new'
  resources :tasks
  resources :users, only:[:new, :create]
  delete 'logout', to: 'sessions#destroy'
  resources :sessions, only:[:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
   belongs_to :user
   validates :status, presence: true, length: { maximum: 10 }
   validates :content, presence: true, length: {maximum: 255 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
   
  include SessionsHelper

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to new_session_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to "/tasks"
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to new_session_url
  end
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = current_user.tasks.all.page(params[:page])
    unless @tasks
      redirect_to new_session_path
    end
  end
   
  def show
  end

  def new
    @task =  current_user.tasks.new
    unless @task
      redirect_to new_session_path
    end
  end

  def create
    @task =  current_user.tasks.new(task_params)
    unless @task
      redirect_to new_session_path
    end
      
    if @task.save
      flash[:success] = 'sample が正常に投稿されました'
      redirect_to @task
    else
      flash.now[:danger] = 'sample が投稿されませんでした'
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      flash[:success] = 'sample は正常に更新されました'
      redirect_to @task
    else
      flash.now[:danger] = 'sample は更新されませんでした'
      render :edit
    end
  end

  def destroy
    @task.destroy

    flash[:success] = 'sample は正常に削除されました'
    redirect_to tasks_url
  end

  private
  
  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to new_session_path
    end
  end

  def task_params
    params.require(:task).permit(:content, :status)
  end
end
  
 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to "/sessions/new"
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
   private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>

<div class="alert alert-<%= message_type %>">
  <%= message %>
</div>

<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <ul class="nav navbar-nav navbar-left">
          <li><%= link_to 'Tasklist', tasks_path %></li>
        </ul>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Signup', new_user_path %></li>
          <% if logged_in? %>
          <li><%= link_to 'Logout', logout_path, method: :delete %></li>
          <% else %>
          <li><%= link_to 'Login', new_session_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Tasklist</title>
    <%= csrf_meta_tags %>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
 <%= form_for(task) do |f| %>
    
  <% if task.errors.any? %>

  <div class="alert alert-warning">
    <ul>
      <% task.errors.full_messages.each do |message| %>

      <li><%= message %></li>
        
      <% end %>
    </ul>
  </div>
    
  <% end %>

  <div class="form-group">
    <%= f.label :status, 'ステータス' %>

    <%= f.text_field :status, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :content, '内容' %>

    <%= f.text_field :content, class: "form-control" %>
  </div>


  
  <%= f.submit '投稿', class: "btn btn-primary"%>
  <% end %>
    
  </br>
  <%= link_to '一覧に戻る', tasks_path, class: "btn btn-primary"%>

app/views/tasks/edit.html.erb
<div class="row">
  <div class="col-sm-offset-2 col-sm-8 col-lg-offset-3 col-lg-6">
    
   <%= render 'layouts/flash_messages' %>
    
   <h1>id: <%= @task.id %> のステータス、内容編集ページ</h1>
   <%= render 'form', task: @task %>
  </div>
</div>
  

app/views/tasks/index.html.erb
<div class="row">
  <div class="col-sm-offset-2 col-sm-8 col-lg-offset-3 col-lg-6">
    
    <%= render 'layouts/flash_messages' %>
    
    <h1>ステータス一覧</h1>

    <% if @tasks.any? %>

      <table class="table table-striped">
        <thead>
          <tr>
            <th>id</th>
            <th>ステータス</th>
            <th>内容</th>
          </tr>
        </thead>

        <tbody>
          <% @tasks.each do |task| %>

          <tr>
            <td><%= link_to task.id, task_path(task) %></td>
            <td><%= task.status %></td>
            <td><%= task.content %></td>
          </tr>
          <% end %>
        </tbody>
     </table>
    <% end %>
    
    <%= paginate @tasks %>
  
    <%= link_to '新規ステータスの投稿', new_task_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="row">
  <div class="col-sm-offset-2 col-sm-8 col-lg-offset-3 col-lg-6">
    
   <%= render 'layouts/flash_messages' %>
    
   <h1>ステータス新規作成ページ</h1>
   <%= render 'form', task: @task %>
  </div>
</div>
  

app/views/tasks/show.html.erb
<div class="row">
  <div class="col-sm-offset-2 col-sm-8 col-lg-offset-3 col-lg-6">
    
    <%= render 'layouts/flash_messages' %>
    
    <h1>id: <%= @task.id %>のステータス、内容詳細ページ</h1>
    <table class="table table-bordered">
      <tr>
        <th>id</th>
        <td><%= @task.id %></td>
      </tr>
      <tr>
        <th>ステータス</th>
        <td><%= @task.status %></td>
      </tr>
      <tr>
        <th>内容</th>
        <td><%= @task.content %></td>
      </tr>
    </table>

    <%= link_to '一覧に戻る', tasks_path, class: "btn btn-primary"%>

    <%= link_to 'このメッセージを編集する', edit_task_path(@task),  class: 'btn btn-default'%>

    <%= link_to 'このメッセージを削除する', @task, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger' %>
  </div>
</div>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-offset-2 col-sm-8 col-lg-offset-3 col-lg-6">

<%= render 'layouts/flash_messages' %>

<%= form_for(@user) do |f| %>

<% if @user.errors.any? %>

  <div class="alert alert-warning">
    <ul>
      <% @user.errors.full_messages.each do |message| %>

      <li><%= message %></li>
        
      <% end %>
    </ul>
  </div>
    
<% end %>


      <div class="form-group">
        
<%= f.label :name, 'Name' %>

        
<%= f.text_field :name, class: 'form-control' %>

      </div>

      <div class="form-group">
        
<%= f.label :email, 'Email' %>

        
<%= f.email_field :email, class: 'form-control' %>

      </div>

      <div class="form-group">
        
<%= f.label :password, 'Password' %>

        
<%= f.password_field :password, class: 'form-control' %>

      </div>

      <div class="form-group">
        
<%= f.label :password_confirmation, 'Confirmation' %>

        
<%= f.password_field :password_confirmation, class: 'form-control' %>

      </div>

      
<%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>

    
<% end %>

  </div>
</div>